from pathlib import Path

from PIL.JpegImagePlugin import RAWMODE

INPUT_FOLDER = Path("data")

MULTIMEDIA_FOLDER = INPUT_FOLDER / "multimedia"
RAW_FOLDER = INPUT_FOLDER / "raw"
PROCESSED_FOLDER = INPUT_FOLDER / "processed"

XML_FOLDER = INPUT_FOLDER / "xml"

ARCHIVE_FOLDER = MULTIMEDIA_FOLDER / "archive"
AUDIO_FOLDER = MULTIMEDIA_FOLDER / "audio"
BOOK_EDITION_FOLDER = MULTIMEDIA_FOLDER / "book_edition"
DOCUMENTATION_FOLDER = MULTIMEDIA_FOLDER / "documentation"
IMAGE_FOLDER = MULTIMEDIA_FOLDER / "image"
IMAGE_ALTERNATIVE_FOLDER = MULTIMEDIA_FOLDER / "image_alternative"
VIDEO_FOLDER = MULTIMEDIA_FOLDER / "video"
